### ISSUE TITLE
Math superset of JSON?

### ISSUE THREAD

**Issue by dy** [endojs/Jessie#66]
Is there a subset in between Jessie and JSON?
![image](https://user-images.githubusercontent.com/300067/136571804-32fd07c2-f30a-4c56-b017-c82d04687cce.png)
Something that takes JSON primitives and enables calc operations, Math superset of JSON?
That JSON+ops syntax is (almost) cross-platform: Rust, Go, C++, C#, Python, Perl? could support that.
That could be a tiny useful thing for any template engines, [template instantiation proposal](https://github.com/WICG/webcomponents/blob/gh-pages/proposals/Template-Instantiation.md), evaluable/calc strings (like css calc), and other playgrounds.

**Comment by erights** [comment]
There is! Justin , defined at https://github.com/agoric-labs/jessica/blob/master/lib/quasi-justin.js.ts

@michaelfig @dckc do we have anything else on Justin?

**Comment by dckc** [comment]
No, that's the only material I know on Justin.

**Comment by dy** [comment]
That's perfect! Is that sort-of compilable, there's no js dist, right?

**Comment by erights** [comment]
That parser should verify that a Justin program is syntactically valid, though we are not currently using that parser or parsing framework in production. Having verified that it is valid Justin syntax, since Justin is a subset of SES, you could then use the SES shim to run it as a SES program. You can use the SES Compartment mechanism to craft the lexical environment that your Justin program sees. I just realized there's one more thing to show you:

https://github.com/Agoric/agoric-sdk/blob/master/packages/marshal/src/marshal-justin.js

tested by

https://github.com/Agoric/agoric-sdk/blob/master/packages/marshal/test/test-marshal-justin.js

This does its round trip tests by evaluating the generated justin program as a SES program in a custom SES environment.

**Comment by dy** [comment]
Just an update. A variation of justin as a separate package [here](https://github.com/spectjs/subscript).

**Comment by JDvorak** [comment]
That would be fantastic. Thank you.

**Comment by dy** [comment]
Ok, for these who's interested - there's [Justin extension](https://github.com/spectjs/subscript#justin) for subscript microlanguage.

**Comment by JDvorak** [comment]
I am so appreciative of this specific extension, thank you again.

**Comment by dy** [comment]
Btw it's called Justin because there's no keyword operators, just _in_.
